services:
  - type: web
    name: fastapi-color-analyzer
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    env: python
    plan: free
